export const mockInventoryData = [
  {
    id: 1,
    category: "bags",
    styles: ["casual"],
    newArrival: true,
    topSelling: false,
    color: "black",
    price: 25.99,
    discountPrice: 12,
  },
  {
    id: 2,
    category: "shoes",
    styles: ["gym"],
    newArrival: false,
    topSelling: true,
    color: "white",
    price: 20,
    discountPrice: 22.49,
  },
  {
    id: 3,
    category: "bags",
    styles: ["formal"],
    newArrival: false,
    topSelling: false,
    color:"ivory",
    price: 16.25,
    discountPrice: 0,
  },
  {
    id: 4,
    category: "bags",
    styles: ["formal"],
    newArrival: false,
    topSelling: true,
    color:"red",
    price: 30.99,
    discountPrice: 5.45,
  },
];